### ISSUE TITLE
Reusing the gRPC Channels

### ISSUE THREAD

**Issue by phiSgr** [REASY/akka-http-vs-akka-grpc#1]
Currently in gatling-grpc every virtual user has its own `ManagedChannel`, which is quite a heavy object.

In your simulation every user only makes one request and goes away. The overhead of channel creation is going to be significant.

It may be better to create users that are not going away,
```scala
rampUsers(120) during 1.second
```

and control the QPS with `.pace`.
```scala
.during(10 minutes) {
  pace(1.second).exec(
    grpc("Get flat type")
      .rpc(ServiceExampleGrpc.METHOD_GET_EMPLOYEE)
      .payload(GetEmployeeRequest(1))
  )
}
```

**Comment by REASY** [comment]
Thanks, @phiSgr. I'll fix that!

**Comment by REASY** [comment]
@phiSgr, I decided to move out from Gatling because I could not make it to keep more than 600 request/s. I moved to https://github.com/giltene/wrk2 for HTTP and https://github.com/bojand/ghz for gRPC. Thank you for your help.
